/**
 * Bundle drizzle migration SQL into a TS module so migrations are embedded in the compiled binary.
 * Run after `drizzle-kit generate`: `bun run --cwd packages/db generate`.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function load(set: "system" | "org") {
  const dir = join(import.meta.dir, "..", "src", set, "drizzle");
  const journal = JSON.parse(readFileSync(join(dir, "meta", "_journal.json"), "utf8")) as {
    entries: { idx: number; tag: string }[];
  };
  return journal.entries
    .sort((a, b) => a.idx - b.idx)
    .map((e) => {
      const sql = readFileSync(join(dir, `${e.tag}.sql`), "utf8");
      return { tag: e.tag, hash: createHash("sha256").update(sql).digest("hex"), sql };
    });
}

const out = `// GENERATED by packages/db/scripts/gen-migrations.ts. Do not edit.
export interface Migration { tag: string; hash: string; sql: string }
export const systemMigrations: Migration[] = ${JSON.stringify(load("system"), null, 2)};
export const orgMigrations: Migration[] = ${JSON.stringify(load("org"), null, 2)};
`;
writeFileSync(join(import.meta.dir, "..", "src", "migrations.gen.ts"), out);
console.log("wrote src/migrations.gen.ts");
