/**
 * Build a single-file executable with the web UI embedded (SPEC §4).
 *
 *   bun scripts/build-binary.ts [--target bun-linux-x64] [--outfile ../../dist/cosimo]
 *     [--version 1.2.3] [--commit abc1234]
 *
 * libsql loads its native addon with a computed require(`@libsql/${target}`), which the bundler
 * cannot follow. A build plugin rewrites it to a static require of the addon for the target
 * platform so the .node file is embedded in the executable (see DECISIONS.md).
 *
 * `--version`/`--commit` (or the env vars COSIMO_VERSION/COSIMO_COMMIT) are baked into the binary
 * as `__COSIMO_VERSION__`/`__COSIMO_COMMIT__` (packages/shared/src/distribution.ts). Without them,
 * the binary reports the dev version and never checks for updates.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { parseArgs } from "node:util";

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    target: { type: "string" },
    outfile: { type: "string" },
    version: { type: "string" },
    commit: { type: "string" },
  },
});

const version = values.version ?? process.env.COSIMO_VERSION;
const commit = values.commit ?? process.env.COSIMO_COMMIT;
// Build metadata (+sha) is allowed alongside a pre-release suffix, such as <last>-dev.<n>+<sha>
// for a build between releases.
if (version && !/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`--version ${version} is not semver X.Y.Z[-pre][+build]`);
}

const here = import.meta.dir;
const root = resolve(here, "..", "..", "..");
const webDist = join(root, "apps", "web", "dist");
const genFile = join(here, "..", "src", "web", "assets.gen.ts");
const stub = `// Placeholder. \`bun run build:binary\` overwrites this with imports of every built web asset
// (embedded into the executable) and restores it afterwards.
export const embeddedAssets: Record<string, string> | null = null;
`;

const hostTarget = `bun-${process.platform === "win32" ? "windows" : process.platform}-${process.arch}`;
const target = values.target ?? hostTarget;
const exe = target.includes("windows") ? ".exe" : "";
const outfile = resolve(
  values.outfile ??
    join(root, "dist", `cosimo${values.target ? `-${target.replace(/^bun-/, "")}` : ""}${exe}`),
);

// Map Bun compile targets to libsql native package names.
const LIBSQL: Record<string, string> = {
  "darwin-arm64": "darwin-arm64",
  "darwin-x64": "darwin-x64",
  "linux-x64": "linux-x64-gnu",
  "linux-arm64": "linux-arm64-gnu",
  "linux-x64-musl": "linux-x64-musl",
  "linux-arm64-musl": "linux-arm64-musl",
  "windows-x64": "win32-x64-msvc",
};
const key = target.replace(/^bun-/, "").replace(/-(baseline|modern)$/, "");
const libsqlPkg = LIBSQL[key];
if (!libsqlPkg) throw new Error(`Unsupported target ${target}`);

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const files = walk(webDist);
if (!files.some((f) => f.endsWith("index.html")))
  throw new Error("apps/web/dist is missing; run `bun run build:web` first");
const imports = files
  .map(
    (f, i) =>
      `import a${i} from ${JSON.stringify(relative(join(here, "..", "src", "web"), f))} with { type: "file" };`,
  )
  .join("\n");
const map = files
  .map((f, i) => `  ${JSON.stringify(relative(webDist, f).replace(/\\/g, "/"))}: a${i},`)
  .join("\n");
writeFileSync(
  genFile,
  `// GENERATED by scripts/build-binary.ts\n${imports}\nexport const embeddedAssets: Record<string, string> | null = {\n${map}\n};\n`,
);

// Only define the version globals when given; left undeclared, distribution.ts's `typeof` check
// falls back to the dev version, so a plain `bun run build:binary` still works during development.
const define: Record<string, string> = { "process.env.COSIMO_COMPILED": '"1"' };
if (version) define.__COSIMO_VERSION__ = JSON.stringify(version);
if (commit) define.__COSIMO_COMMIT__ = JSON.stringify(commit);

try {
  const result = await Bun.build({
    entrypoints: [join(here, "..", "src", "cli", "main.ts")],
    compile: { target: target as never, outfile },
    minify: true,
    sourcemap: "none",
    define,
    plugins: [
      {
        name: "libsql-static-native",
        setup(b) {
          b.onLoad({ filter: /[\\/]node_modules[\\/]libsql[\\/]index\.js$/ }, async (args) => {
            const src = await Bun.file(args.path).text();
            const patched = src.replace(
              "return require(`@libsql/${target}`);",
              `return require("@libsql/${libsqlPkg}");`,
            );
            if (patched === src) throw new Error("libsql loader pattern not found; update build-binary.ts");
            return { contents: patched, loader: "js" };
          });
        },
      },
    ],
  });
  if (!result.success) {
    for (const l of result.logs) console.error(String(l));
    process.exit(1);
  }
  console.log(`built ${outfile} (${target})`);
} finally {
  writeFileSync(genFile, stub);
}
